import Head from "next/head";

import GlowingButton from "@/components/GlowingButton";

export default function Home() {
	return (
		<>
			<Head>
				<title>Work</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<GlowingButton />
			</main>
		</>
	);
}
